# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#Token JWT
jwt.access-token.secret=${ACCESSTOKEN_SECRET}
jwt.access-token.time=${ACCESSTOKEN_TIME}
jwt.refresh-token.secret=${REFRESHTOKEN_SECRET}
jwt.refresh-token.time=${REFRESHTOKEN_TIME}

#CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

#Flyway
spring.flyway.clean-disabled=true

#AI
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=${GEMINI_MODEL}