#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bufonio
spring.datasource.username=root
spring.datasource.password=bufonio

#Token JWT
jwt.access-token.secret=MyAccessTokenSecret
jwt.access-token.time=900000
jwt.refresh-token.secret=MyRefreshTokeSecret
jwt.refresh-token.time=604800000

#CORS
app.cors.allowed-origins=http://localhost:5173

#Flyway
spring.flyway.clean-disabled=false

#AI
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=${GEMINI_MODEL}